openapi: 3.0.1
info:
  title: Gateway Grpc Service
  version: v1
  description: |-
    This is a development API for testing the feasability of using GRPC for Gatway communications in the new Warehouse Management System for The British Library.
    
    You can fins the source code of this API on GitHub [here](https://github.com/thattonBL/GatewayGrpcService)
    
    There is plenty more work to do on this, in particular to see if the bi-directional streaming capabilities of GRPC are going to be of use for these sorts of communications.
paths:
  /gateway:
    get:
      tags:
        - GatewayGrpcService
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RSIMessage'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
components:
  schemas:
    Any:
      required:
        - '@type'
      type: object
      properties:
        '@type':
          type: string
      additionalProperties: {}
    RSIMessage:
      type: object
      properties:
        id:
          type: integer
          format: int32
        collectionCode:
          type: string
        shelfmark:
          type: string
        volumeNumber:
          type: string
        storageLocationCode:
          type: string
        author:
          type: string
        title:
          type: string
        publicationDate:
          type: string
        periodicalDate:
          type: string
        articleLine1:
          type: string
        articleLine2:
          type: string
        catalogueRecordUrl:
          type: string
        furtherDetailsUrl:
          type: string
        dtRequired:
          type: string
        route:
          type: string
        readingRoomStaffArea:
          type: string
        seatNumber:
          type: string
        readingCategory:
          type: string
        identifier:
          type: string
        readerName:
          type: string
        readerType:
          type: integer
          format: int32
        operatorInformation:
          type: string
        itemIdentity:
          type: string
      additionalProperties: false
    Status:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/Any'
      additionalProperties: false
