name: Trigger auto deployment for b33mockapicontapp1

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/b33mockapicontapp1-AutoDeployTrigger-0a5756b5-ed96-4351-a7fa-2bcb1ca73208.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.B33MOCKAPICONTAPP1_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.B33MOCKAPICONTAPP1_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.B33MOCKAPICONTAPP1_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: building33mockapi20240524110656.azurecr.io
          registryUsername: ${{ secrets.B33MOCKAPICONTAPP1_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.B33MOCKAPICONTAPP1_REGISTRY_PASSWORD }}
          containerAppName: b33mockapicontapp1
          resourceGroup: GatewayResources
          imageToBuild: building33mockapi20240524110656.azurecr.io/b33mockapicontapp1:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


